# Version
version: '1.0'
debug: False

# Country mappings for Americas and Caribbean regions
countries:
  Canada: CAN
  # Mexico: MEX

# world bank api information
world_bank_api:
  output_path: worldbank
  metadata_attributes:
    - id
    - IndicatorName
    - Source
    - License_Type
    - License_URL
    - Longdefinition
    - Unitofmeasure
  # SAC indicators and their World Bank Group id's
  indicators:
    - EN.GHG.CO2.PC.CE.AR5  # CO2 emissions per capita
    # - EN.GHG.ALL.PC.CE.AR5  # Total GHG emissions per capita



# Our World in Data configuration
owid_api:
  output_path: owid
  # GitHub repository contains the datasets
  metadata_url: https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-codebook.csv 
  data_url: https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv
  # interesting attributes from the metadata
  metadata_attributes:
    - column
    - description
    - unit
    - source
  # selected indicators 
  indicators:
    - population

# date range for data retrieval
date_range:
  start_year: 2000
  end_year: 2001

