name: Test data pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**


jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Load the repository (GitHub Action)
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'    

    - name: Make test script executable
      run: chmod +x project/tests.sh
    
    - name: Run tests
      run: cd project && ./tests.sh